version: '3.8'
services:
  api:
    image: alanh0/reactdocker_api
    container_name: api_backend
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
  client:
    image: alanh0/reactdocker_client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true