name: Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          cd api
          docker build -t alanh0/reactdocker_api:latest -t alanh0/reactdocker_api:latest .
          docker push alanh0/reactdocker_api:latest .
          cd client
          docker build -t alanh0/reactdocker_client:latest .
          docker push alanh0/reactdocker_client:latest 
